In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

RANDOM_STATE = 42

In [ ]:
from pathlib import Path

RAW_DATA_PATH = Path("/content/survey_responses_raw.csv")
PROCESSED_DIR = Path("/content/processed")

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [ ]:
df_raw = pd.read_csv(RAW_DATA_PATH)

print("Raw dataset shape:", df_raw.shape)
display(df_raw.head())

Raw dataset shape: (467, 45)

,respondent_id,language,submitted_at,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42
0,056oT1N5noG31qI1cLeN,Sinhala,2026-08-14 05:20:22.515000+00:00,18,පුරුෂ,කිසිදා විවාහ වී නොමැත,6,G.C.E සාමාන්‍ය පෙළ (O/L),"වෘත්තීය කුසලතා (උදා: ආහාරපාන සේවා, යාන්ත්‍රික,...",මාස 12කට වඩා වැඩියි,මධ්‍යම,සීමිත ප්‍රවේශයක් (උදා: දුරකථනයෙන් පමණි),සිංහල,3 — මධ්‍යම,3 — මධ්‍යස්ථ විශ්වාසයක් ඇත,සමහර විට,නැත,NaN,NaN,NaN,NaN,සුදුසු වැඩසටහනක් සොයාගත නොහැකි විය,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,රැකියා විරහිත නමුත් දැනට රැකියාවක් සොයන්නේ නැත,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,වෘත්තීය / කාර්මික පුහුණුව,NaN,NaN
1,0jV4sV7bmOPyaamon1Wn,English,2026-07-31 10:10:09.966000+00:00,24,Female,Diploma / Higher National Diploma,Engineering / Technology,Less than 6 months,North Western,Good (Regular access),4,2,2,3,4,3,2,3,4,Unemployed (actively looking for work / not cu...,I have been actively looking for work (less th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0lnyyVVLAbCpLL2HA7LU,English,2026-08-14 05:35:59.272000+00:00,21,Female,Prefer not to say,5,G.C.E. Advanced Level (A/Level),Information Technology / Computer Science,More than 12 months,Central,Good (Regular access),Sinhala | English,4 — Good,4 — Confident,Often,No,NaN,NaN,NaN,NaN,I am currently studying,4.0,3.0,4.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,Full-time student and not currently looking fo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,3 — Moderately prepared
3,0qJX2sQRhn57GDCN1V50,Sinhala,2026-08-14 05:10:46.089000+00:00,22,පුරුෂ,කිසිදා විවාහ වී නොමැත,4,G.C.E උසස් පෙළ (A/L),"වෘත්තීය කුසලතා (උදා: ආහාරපාන සේවා, යාන්ත්‍රික,...",මාස 12කට වඩා වැඩියි,මධ්‍යම,සීමිත ප්‍රවේශයක් (උදා: දුරකථනයෙන් පමණි),සිංහල,1 — ඉතා අඩු,3 — මධ්‍යස්ථ විශ්වාසයක් ඇත,සමහර විට,නැත,NaN,NaN,NaN,NaN,මම දැනට අධ්‍යාපනය ලබමින් සිටිමි,3.0,3.0,3.0,3.0,4.0,2.0,4.0,4.0,3.0,3.0,පූර්ණ කාලීන ශිෂ්‍යයෙකු වන අතර දැනට රැකියාවක් ස...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ඔව්,2 — සුළු වශයෙන් සූදානම්
4,13FtTDlmW2WGWDny4fn0,Tamil,2026-08-14 05:57:29.148000+00:00,28,பெண்,ஒருபோதும் திருமணம் ஆகவில்லை,5,G.C.E சாதாரண தரம் (O/L),கலை / மனிதநேயம் / சமூக அறிவியல்,12 மாதங்களுக்கும் அதிகம்,மத்திய,வரையறுக்கப்பட்ட அணுகல் (மொபைல் மட்டும்),ஆங்கிலம் | தமிழ் | சிங்களம்,4 — நல்லது,3 — மிதமான நம்பிக்கை,அடிக்கடி,ஆம்,பயிற்சிநிலை / தொழில்நுட்பப் பயிற்சி,அழகு / தனிப்பட்ட பராமரிப்பு,1 வருடத்திற்கும் மேல்,சிறிதளவு தொடர்புடையது,NaN,5.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,5.0,5.0,வேலை செய்பவர் / சுயதொழில் செய்பவர் / வணிக உரிம...,3–6 மாதங்கள்,தனிப்பட்ட ஒப்பந்தப் பணி (Freelancing) / பணியடி...,மிகவும் தொடர்புடையது,திருப்தி,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print("Number of respondents:", len(df_raw))
print("Number of columns:", len(df_raw.columns))

print("\nSurvey languages:")
print(df_raw["language"].value_counts(dropna=False))

print("\nMissing Q30:")
print(df_raw["q30"].isna().value_counts())

Number of respondents: 467
Number of columns: 45

Survey languages:
language
Sinhala    278
Tamil      101
English     88
Name: count, dtype: int64

Missing Q30:
q30
False    456
True      11
Name: count, dtype: int64

In [ ]:
EMPLOYED_Q30 = {
    "Employed / Self-employed / Business owner / Freelancing / Gig work",

    "රැකියාවක නියුක්ත / ස්වයං රැකියාවක නියුක්ත / ව්‍යාපාර හිමිකරු / නිදහස් සේවා (Freelancing) / කෙටි කාලීන හෝ කාර්ය පදනම් රැකියා (Gig work)",

    "வேலை செய்பவர் / சுயதொழில் செய்பவர் / வணிக உரிமையாளர் / தனிப்பட்ட ஒப்பந்தப் பணி (Freelancing) / குறுகியகால அல்லது பணியடிப்படையிலான வேலை (Gig work)"
}


ACTIVE_UNEMPLOYED_Q30 = {
    "Unemployed and actively looking for work",

    "රැකියා විරහිත අතර සක්‍රීයව රැකියාවක් සොයමින් සිටී",

    "வேலையில்லாமல் இருப்பதுடன் தீவிரமாக வேலை தேடிக்கொண்டிருக்கிறார்"
}


NOT_LOOKING_Q30 = {
    "Unemployed but not currently looking for work",

    "රැකියා විරහිත නමුත් දැනට රැකියාවක් සොයන්නේ නැත",

    "வேலையில்லாமல் இருக்கிறார், ஆனால் தற்போது வேலை தேடவில்லை"
}


STUDENT_Q30 = {
    "Full-time student and not currently looking for work",

    "පූර්ණ කාලීන ශිෂ්‍යයෙකු වන අතර දැනට රැකියාවක් සොයන්නේ නැත",

    "முழுநேர மாணவராக இருப்பதுடன் தற்போது வேலை தேடவில்லை"
}


VALID_Q30 = (
    EMPLOYED_Q30
    | ACTIVE_UNEMPLOYED_Q30
    | NOT_LOOKING_Q30
    | STUDENT_Q30
)

In [ ]:
df_raw["is_current_schema"] = df_raw["q30"].isin(VALID_Q30)

schema_summary = (
    df_raw["is_current_schema"]
    .value_counts()
    .rename(index={
        True: "Current schema",
        False: "Legacy / incompatible schema"
    })
)

print(schema_summary)

df_legacy = df_raw.loc[~df_raw["is_current_schema"]].copy()

df_legacy.to_csv(
    PROCESSED_DIR / "legacy_schema_responses.csv",
    index=False,
    encoding="utf-8-sig"
)

df = df_raw.loc[df_raw["is_current_schema"]].copy()

print("Current-schema dataset:", df.shape)

is_current_schema
Current schema                  456
Legacy / incompatible schema     11
Name: count, dtype: int64
Current-schema dataset: (456, 46)

In [ ]:
COLUMN_MAP = {
    "q1": "age",
    "q2": "gender",
    "q3": "marital_status",
    "q4": "household_size",
    "q5": "education_level",
    "q6": "field_of_study",
    "q7": "time_since_studies",
    "q8": "province",
    "q9": "digital_access",
    "q10": "languages_read_write",
    "q11": "english_communication",
    "q12": "digital_confidence",
    "q13": "internet_use_frequency",
    "q14": "formal_training",
    "q15": "training_type",
    "q16": "training_field",
    "q17": "training_duration",
    "q18": "training_relevance",
    "q19": "reason_no_training",

    "q20": "analytical_thinking",
    "q21": "resilience_flexibility_agility",
    "q22": "leadership_social_influence",
    "q23": "creative_thinking",
    "q24": "motivation_self_awareness",
    "q25": "technological_literacy",
    "q26": "empathy_active_listening",
    "q27": "curiosity_lifelong_learning",
    "q28": "talent_management",
    "q29": "service_orientation",

    "q30": "employment_status",
    "q31": "time_to_first_job",
    "q32": "current_work_type",
    "q33": "work_education_relevance",
    "q34": "employment_satisfaction",
    "q35": "job_search_duration",
    "q36": "recent_job_search_action",
    "q37": "job_search_methods",
    "q38": "employment_barrier",
    "q39": "available_within_two_weeks",
    "q40": "reason_not_looking",
    "q41": "intend_seek_after_studies",
    "q42": "workforce_preparedness",
}

df = df.rename(columns=COLUMN_MAP)

In [ ]:
def canonical_employment_status(value):

    if value in EMPLOYED_Q30:
        return "employed"

    if value in ACTIVE_UNEMPLOYED_Q30:
        return "active_unemployed"

    if value in NOT_LOOKING_Q30:
        return "not_looking"

    if value in STUDENT_Q30:
        return "full_time_student"

    return np.nan


df["employment_status_canonical"] = (
    df["employment_status"]
    .apply(canonical_employment_status)
)

print(
    df["employment_status_canonical"]
    .value_counts(dropna=False)
)

employment_status_canonical
full_time_student    180
active_unemployed    157
employed              91
not_looking           28
Name: count, dtype: int64

In [ ]:
YES_VALUES = {
    "Yes",
    "ඔව්",
    "ஆம்"
}

NO_VALUES = {
    "No",
    "නැත",
    "இல்லை"
}


def canonical_yes_no(value):

    if value in YES_VALUES:
        return "yes"

    if value in NO_VALUES:
        return "no"

    return np.nan


df["recent_job_search_action_canonical"] = (
    df["recent_job_search_action"]
    .apply(canonical_yes_no)
)

df["available_within_two_weeks_canonical"] = (
    df["available_within_two_weeks"]
    .apply(canonical_yes_no)
)

In [ ]:
def assign_labour_market_group(row):

    status = row["employment_status_canonical"]
    recent_search = row["recent_job_search_action_canonical"]
    available = row["available_within_two_weeks_canonical"]

    # Class 1 candidate
    if status == "employed":
        return "EMPLOYED"

    # Strict primary negative class:
    # actively unemployed + evidence of recent search activity
    if (
        status == "active_unemployed"
        and recent_search == "yes"
    ):
        return "ACTIVE_UNEMPLOYED_RECENT_SEARCH"

    # Actively-unemployed self-report but no recent search action.
    # Keep separate for sensitivity analysis.
    if (
        status == "active_unemployed"
        and recent_search == "no"
        and available == "yes"
    ):
        return "AVAILABLE_NOT_RECENTLY_SEARCHING"

    if (
        status == "active_unemployed"
        and recent_search == "no"
        and available == "no"
    ):
        return "NOT_SEARCHING_NOT_AVAILABLE"

    if status == "not_looking":
        return "OUTSIDE_PRIMARY_LABOUR_FORCE"

    if status == "full_time_student":
        return "FULL_TIME_STUDENT"

    return "UNCLASSIFIED"


df["labour_market_group"] = df.apply(
    assign_labour_market_group,
    axis=1
)

print(
    df["labour_market_group"]
    .value_counts()
)

labour_market_group
FULL_TIME_STUDENT                   180
ACTIVE_UNEMPLOYED_RECENT_SEARCH     101
EMPLOYED                             91
AVAILABLE_NOT_RECENTLY_SEARCHING     45
OUTSIDE_PRIMARY_LABOUR_FORCE         28
NOT_SEARCHING_NOT_AVAILABLE          11
Name: count, dtype: int64

In [ ]:
PRIMARY_GROUPS = {
    "EMPLOYED",
    "ACTIVE_UNEMPLOYED_RECENT_SEARCH"
}

df["eligible_primary_model"] = (
    df["labour_market_group"]
    .isin(PRIMARY_GROUPS)
)

df["employment_outcome"] = np.where(
    df["labour_market_group"] == "EMPLOYED",
    1,
    np.where(
        df["labour_market_group"] == "ACTIVE_UNEMPLOYED_RECENT_SEARCH",
        0,
        np.nan
    )
)

print("Current-schema respondents:", len(df))

print(
    "\nLabour-market groups:"
)

print(
    df["labour_market_group"]
    .value_counts()
)

print(
    "\nEligible for primary binary model:",
    df["eligible_primary_model"].sum()
)

Current-schema respondents: 456

Labour-market groups:
labour_market_group
FULL_TIME_STUDENT                   180
ACTIVE_UNEMPLOYED_RECENT_SEARCH     101
EMPLOYED                             91
AVAILABLE_NOT_RECENTLY_SEARCHING     45
OUTSIDE_PRIMARY_LABOUR_FORCE         28
NOT_SEARCHING_NOT_AVAILABLE          11
Name: count, dtype: int64

Eligible for primary binary model: 192

In [ ]:
df_model = (
    df.loc[df["eligible_primary_model"]]
    .copy()
)

df_model["employment_outcome"] = (
    df_model["employment_outcome"]
    .astype(int)
)

print("Primary modelling sample:", len(df_model))

print("\nTarget distribution:")
print(
    df_model["employment_outcome"]
    .value_counts()
    .sort_index()
)

print("\nTarget percentages:")
print(
    df_model["employment_outcome"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

Primary modelling sample: 192

Target distribution:
employment_outcome
0    101
1     91
Name: count, dtype: int64

Target percentages:
employment_outcome
0    52.6
1    47.4
Name: proportion, dtype: float64

In [ ]:
SKILL_FEATURES = [
    "analytical_thinking",
    "resilience_flexibility_agility",
    "leadership_social_influence",
    "creative_thinking",
    "motivation_self_awareness",
    "technological_literacy",
    "empathy_active_listening",
    "curiosity_lifelong_learning",
    "talent_management",
    "service_orientation",
]

for col in SKILL_FEATURES:
    df_model[col] = pd.to_numeric(
        df_model[col],
        errors="coerce"
    )

for col in SKILL_FEATURES:

    invalid = df_model.loc[
        ~df_model[col].between(1, 5)
        & df_model[col].notna(),
        col
    ]

    if len(invalid) > 0:
        print(col, invalid.unique())

**Define Model A**

In [ ]:
MODEL_A_FEATURES = SKILL_FEATURES.copy()

print("Model A features:")
for feature in MODEL_A_FEATURES:
    print("-", feature)

Model A features:
- analytical_thinking
- resilience_flexibility_agility
- leadership_social_influence
- creative_thinking
- motivation_self_awareness
- technological_literacy
- empathy_active_listening
- curiosity_lifelong_learning
- talent_management
- service_orientation

In [ ]:
MODEL_B_ADDITIONAL_FEATURES = [

    # Demographic
    "age",
    "gender",
    "marital_status",
    "household_size",

    # Education / human capital
    "education_level",
    "field_of_study",
    "time_since_studies",

    # Structural / contextual
    "province",
    "digital_access",
    "english_communication",
    "digital_confidence",

    # Training-related
    "formal_training",
    "training_type",
    "training_field",
    "training_duration",
    "training_relevance",
]

MODEL_B_FEATURES = (
    MODEL_A_FEATURES
    + MODEL_B_ADDITIONAL_FEATURES
)

print("Model B feature count:", len(MODEL_B_FEATURES))

for feature in MODEL_B_FEATURES:
    print("-", feature)

Model B feature count: 26
- analytical_thinking
- resilience_flexibility_agility
- leadership_social_influence
- creative_thinking
- motivation_self_awareness
- technological_literacy
- empathy_active_listening
- curiosity_lifelong_learning
- talent_management
- service_orientation
- age
- gender
- marital_status
- household_size
- education_level
- field_of_study
- time_since_studies
- province
- digital_access
- english_communication
- digital_confidence
- formal_training
- training_type
- training_field
- training_duration
- training_relevance

In [ ]:
df_model["age"] = pd.to_numeric(
    df_model["age"],
    errors="coerce"
)

HOUSEHOLD_SIZE_MAP = {
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,

    "7 or more": 7,
    "7 හෝ ඊට වැඩි": 7,
    "7 அல்லது அதற்கு மேல்": 7,
}

df_model["household_size"] = (
    df_model["household_size"]
    .map(HOUSEHOLD_SIZE_MAP)
)

print("Age values:")
print(df_model["age"].value_counts(dropna=False).sort_index())

print("\nHousehold size:")
print(df_model["household_size"].value_counts(dropna=False).sort_index())

Age values:
age
18    21
19    13
20     8
21    32
22     8
23    12
24    12
25    27
26    10
27    19
28    15
29    15
Name: count, dtype: int64

Household size:
household_size
1     1
2     9
3    37
4    66
5    39
6    22
7    18
Name: count, dtype: int64

In [ ]:
def extract_likert_number(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if len(value) > 0 and value[0] in {"1", "2", "3", "4", "5"}:
        return int(value[0])

    return np.nan


for col in [
    "english_communication",
    "digital_confidence",
]:
    df_model[col] = df_model[col].apply(
        extract_likert_number
    )

for col in [
    "english_communication",
    "digital_confidence",
]:
    print("\n", col)
    print(df_model[col].value_counts(dropna=False).sort_index())

 english_communication
english_communication
1    18
2    16
3    92
4    55
5    11
Name: count, dtype: int64

 digital_confidence
digital_confidence
1     1
2    10
3    53
4    91
5    37
Name: count, dtype: int64

In [ ]:
def canonical_formal_training(value):

    if value in {"Yes", "ඔව්", "ஆம்"}:
        return "Yes"

    if value in {"No", "නැත", "இல்லை"}:
        return "No"

    return np.nan


df_model["formal_training"] = (
    df_model["formal_training"]
    .apply(canonical_formal_training)
)

print(
    df_model["formal_training"]
    .value_counts(dropna=False)
)

formal_training
No     101
Yes     91
Name: count, dtype: int64

In [ ]:
TRAINING_DETAIL_FEATURES = [
    "training_type",
    "training_field",
    "training_duration",
    "training_relevance",
]

for col in TRAINING_DETAIL_FEATURES:

    df_model.loc[
        df_model["formal_training"] == "No",
        col
    ] = "NOT_APPLICABLE_NO_FORMAL_TRAINING"

for col in TRAINING_DETAIL_FEATURES:

    print("\n" + "=" * 60)
    print(col)

    print(
        df_model[col]
        .value_counts(dropna=False)
        .head(20)
    )

============================================================
training_type
training_type
NOT_APPLICABLE_NO_FORMAL_TRAINING      101
NVQ                                     45
Professional qualification               7
ඩිප්ලෝමාව                                5
Higher Diploma                           5
උසස් ඩිප්ලෝමාව                           4
டிப்ளோமா                                 4
பயிற்சிநிலை / தொழில்நுட்பப் பயிற்சி      3
වෙනත්                                    3
Certificate course                       3
Diploma                                  3
සහතික පාඨමාලාව                           2
உயர் டிப்ளோமா                            2
தொழில்முறை தகுதி                         2
Apprenticeship / Technical training      1
சான்றிதழ் பாடநெறி                        1
වෘත්තීය සුදුසුකම                         1
Name: count, dtype: int64

============================================================
training_field
training_field
NOT_APPLICABLE_NO_FORMAL_TRAINING    101
விவசாயம்                              17
வேறு                                  10
තොරතුරු තාක්ෂණය                        9
Information Technology                 8
වෙනත්                                  6
Business / Management                  6
ව්‍යාපාර / කළමනාකරණය                   4
ආගන්තුක සත්කාර / සංචාරක ව්‍යාපාරය      4
සෞඛ්‍ය සේවා                            4
Hospitality / Tourism                  4
விருந்தோம்பல் / சுற்றுலா               3
Construction                           3
அழகு / தனிப்பட்ட பராமரிப்பு            2
தகவல் தொழில்நுட்பம்                    2
வாகன / இயந்திரவியல்                    2
Agriculture                            2
ඉදිකිරීම්                              1
கட்டுமானம்                             1
Other                                  1
Name: count, dtype: int64

============================================================
training_duration
training_duration
NOT_APPLICABLE_NO_FORMAL_TRAINING    101
6–12 மாதங்கள்                         21
මාස 6–12                              11
More than 1 year                      11
1 வருடத்திற்கும் மேல்                 10
6–12 months                            8
වසර 1කට වැඩි                           8
මාස 3කට අඩු                            6
මාස 3–6                                5
3–6 மாதங்கள்                           4
3–6 months                             4
3 மாதங்களுக்கும் குறைவாக               2
Less than 3 months                     1
Name: count, dtype: int64

============================================================
training_relevance
training_relevance
NOT_APPLICABLE_NO_FORMAL_TRAINING    101
மிகவும் தொடர்புடையது                  20
ඉතා අදාළයි                            16
Very relevant                         10
අතිශයින් අදාළයි                        8
Highly relevant                        7
மிக அதிகமாக தொடர்புடையது               6
சிறிதளவு தொடர்புடையது                  6
Moderately relevant                    6
மிதமாக தொடர்புடையது                    4
මධ්‍යස්ථව අදාළයි                       4
සුළු වශයෙන් අදාළයි                     2
Not relevant                           1
தொடர்பில்லை                            1
Name: count, dtype: int64

In [ ]:
trained = df_model[
    df_model["formal_training"] == "Yes"
]

print("Respondents with formal training:", len(trained))

for col in TRAINING_DETAIL_FEATURES:

    missing_count = trained[col].isna().sum()

    print(
        col,
        "genuine missing among trained respondents:",
        missing_count
    )

Respondents with formal training: 91
training_type genuine missing among trained respondents: 0
training_field genuine missing among trained respondents: 0
training_duration genuine missing among trained respondents: 0
training_relevance genuine missing among trained respondents: 0

In [ ]:
for col in MODEL_A_FEATURES:

    df_model[col] = pd.to_numeric(
        df_model[col],
        errors="coerce"
    )

In [ ]:
skill_quality = pd.DataFrame({
    "missing": df_model[MODEL_A_FEATURES].isna().sum(),
    "min": df_model[MODEL_A_FEATURES].min(),
    "max": df_model[MODEL_A_FEATURES].max(),
})

display(skill_quality)

                                missing  min  max
analytical_thinking                   1  1.0  5.0
resilience_flexibility_agility        0  1.0  5.0
leadership_social_influence           0  1.0  5.0
creative_thinking                     0  1.0  5.0
motivation_self_awareness             0  1.0  5.0
technological_literacy                0  1.0  5.0
empathy_active_listening              0  1.0  5.0
curiosity_lifelong_learning           0  1.0  5.0
talent_management                     0  1.0  5.0
service_orientation                   0  1.0  5.0

In [ ]:
model_a_missing = (
    df_model[MODEL_A_FEATURES]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    model_a_missing.to_frame("missing_count")
)

                                missing_count
analytical_thinking                         1
resilience_flexibility_agility              0
leadership_social_influence                 0
creative_thinking                           0
motivation_self_awareness                   0
technological_literacy                      0
empathy_active_listening                    0
curiosity_lifelong_learning                 0
talent_management                           0
service_orientation                         0

In [ ]:
model_b_missing = (
    df_model[MODEL_B_FEATURES]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    model_b_missing.to_frame("missing_count")
)

                                missing_count
analytical_thinking                         1
resilience_flexibility_agility              0
leadership_social_influence                 0
creative_thinking                           0
motivation_self_awareness                   0
technological_literacy                      0
empathy_active_listening                    0
curiosity_lifelong_learning                 0
talent_management                           0
service_orientation                         0
age                                         0
gender                                      0
marital_status                              0
household_size                              0
education_level                             0
field_of_study                              0
time_since_studies                          0
province                                    0
digital_access                              0
english_communication                       0
digital_confidence                          0
formal_training                             0
training_type                               0
training_field                              0
training_duration                           0
training_relevance                          0

In [ ]:
feature_spec = pd.DataFrame({

    "feature": MODEL_B_FEATURES,

    "model_a": [
        feature in MODEL_A_FEATURES
        for feature in MODEL_B_FEATURES
    ],

    "model_b": True
})

display(feature_spec)

                           feature  model_a  model_b
0              analytical_thinking     True     True
1   resilience_flexibility_agility     True     True
2      leadership_social_influence     True     True
3                creative_thinking     True     True
4        motivation_self_awareness     True     True
5           technological_literacy     True     True
6         empathy_active_listening     True     True
7      curiosity_lifelong_learning     True     True
8                talent_management     True     True
9              service_orientation     True     True
10                             age    False     True
11                          gender    False     True
12                  marital_status    False     True
13                  household_size    False     True
14                 education_level    False     True
15                  field_of_study    False     True
16              time_since_studies    False     True
17                        province    False     True
18                  digital_access    False     True
19           english_communication    False     True
20              digital_confidence    False     True
21                 formal_training    False     True
22                   training_type    False     True
23                  training_field    False     True
24               training_duration    False     True
25              training_relevance    False     True

In [ ]:
OUTPUT_PATH = (
    PROCESSED_DIR
    / "primary_model_dataset_prepared.csv"
)

df_model.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:")
print(OUTPUT_PATH)

print("\nShape:")
print(df_model.shape)

Saved:
/content/processed/primary_model_dataset_prepared.csv

Shape:
(192, 52)

In [ ]:
target_counts = (
    df_model["employment_outcome"]
    .value_counts()
    .sort_index()
)

target_percentages = (
    df_model["employment_outcome"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

target_summary = pd.DataFrame({
    "count": target_counts,
    "percentage": target_percentages
})

display(target_summary)

print("Total modelling respondents:", len(df_model))

                    count  percentage
employment_outcome
0                     101        52.6
1                      91        47.4

Total modelling respondents: 192

In [ ]:
duplicate_ids = df_model["respondent_id"].duplicated().sum()

print("Duplicate respondent IDs:", duplicate_ids)

Duplicate respondent IDs: 0

In [ ]:
print("RAW dataset age values:")

raw_age = pd.to_numeric(df_raw["q1"], errors="coerce")

print("Min:", raw_age.min())
print("Max:", raw_age.max())

print("\nCounts by age:")
print(raw_age.value_counts().sort_index())

RAW dataset age values:
Min: 18
Max: 29

Counts by age:
q1
18    152
19     49
20     32
21     53
22     17
23     22
24     31
25     35
26     15
27     21
28     23
29     17
Name: count, dtype: int64

In [ ]:
print("Age:")
print("Min:", df_model["age"].min())
print("Max:", df_model["age"].max())

print("\nHousehold size:")
print("Min:", df_model["household_size"].min())
print("Max:", df_model["household_size"].max())

print("\nEnglish communication:")
print("Min:", df_model["english_communication"].min())
print("Max:", df_model["english_communication"].max())

print("\nDigital confidence:")
print("Min:", df_model["digital_confidence"].min())
print("Max:", df_model["digital_confidence"].max())

print("\n10 skill ranges:")

for col in MODEL_A_FEATURES:
    print(
        f"{col}: "
        f"{df_model[col].min()} – {df_model[col].max()}"
    )

Age:
Min: 18
Max: 29

Household size:
Min: 1
Max: 7

English communication:
Min: 1
Max: 5

Digital confidence:
Min: 1
Max: 5

10 skill ranges:
analytical_thinking: 1.0 – 5.0
resilience_flexibility_agility: 1.0 – 5.0
leadership_social_influence: 1.0 – 5.0
creative_thinking: 1.0 – 5.0
motivation_self_awareness: 1.0 – 5.0
technological_literacy: 1.0 – 5.0
empathy_active_listening: 1.0 – 5.0
curiosity_lifelong_learning: 1.0 – 5.0
talent_management: 1.0 – 5.0
service_orientation: 1.0 – 5.0

In [ ]:
final_missing = (
    df_model[MODEL_B_FEATURES + ["employment_outcome"]]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    final_missing.to_frame("missing_count")
)

                                missing_count
analytical_thinking                         1
resilience_flexibility_agility              0
leadership_social_influence                 0
creative_thinking                           0
motivation_self_awareness                   0
technological_literacy                      0
empathy_active_listening                    0
curiosity_lifelong_learning                 0
talent_management                           0
service_orientation                         0
age                                         0
gender                                      0
marital_status                              0
household_size                              0
education_level                             0
field_of_study                              0
time_since_studies                          0
province                                    0
digital_access                              0
english_communication                       0
digital_confidence                          0
formal_training                             0
training_type                               0
training_field                              0
training_duration                           0
training_relevance                          0
employment_outcome                          0

In [ ]:
missing_analytical = df_model[
    df_model["analytical_thinking"].isna()
]

print("Number of affected respondents:", len(missing_analytical))

display(
    missing_analytical[
        [
            "respondent_id",
            "language",
            "analytical_thinking",
            "resilience_flexibility_agility",
            "leadership_social_influence",
            "creative_thinking",
            "motivation_self_awareness",
            "technological_literacy",
            "empathy_active_listening",
            "curiosity_lifelong_learning",
            "talent_management",
            "service_orientation",
            "employment_outcome"
        ]
    ]
)

Number of affected respondents: 1

,respondent_id,language,analytical_thinking,resilience_flexibility_agility,leadership_social_influence,creative_thinking,motivation_self_awareness,technological_literacy,empathy_active_listening,curiosity_lifelong_learning,talent_management,service_orientation,employment_outcome
259,ZFOYDvTN6DKqir4ohVqe,English,NaN,4.0,5.0,4.0,5.0,4.0,5.0,4.0,4.0,5.0,1

In [ ]:
affected_ids = missing_analytical["respondent_id"].tolist()

display(
    df_raw.loc[
        df_raw["respondent_id"].isin(affected_ids),
        ["respondent_id", "language", "q20", "q21", "q22", "q23", "q24",
         "q25", "q26", "q27", "q28", "q29"]
    ]
)

,respondent_id,language,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29
259,ZFOYDvTN6DKqir4ohVqe,English,NaN,4.0,5.0,4.0,5.0,4.0,5.0,4.0,4.0,5.0

In [ ]:
# ---------------------------------------------------------
# Remove respondents missing any core Model A skill
# ---------------------------------------------------------

n_before = len(df_model)

missing_core_skill = (
    df_model[MODEL_A_FEATURES]
    .isna()
    .any(axis=1)
)

print("Respondents with missing core skill data:",
      missing_core_skill.sum())

# Keep an audit copy of excluded records
df_missing_core_skills = (
    df_model.loc[missing_core_skill]
    .copy()
)

# Complete-case modelling dataset
df_model = (
    df_model.loc[~missing_core_skill]
    .copy()
    .reset_index(drop=True)
)

n_after = len(df_model)

print("Before exclusion:", n_before)
print("After exclusion:", n_after)
print("Removed:", n_before - n_after)

Respondents with missing core skill data: 1
Before exclusion: 192
After exclusion: 191
Removed: 1

In [ ]:
df_missing_core_skills.to_csv(
    PROCESSED_DIR / "excluded_missing_core_skills.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Excluded record saved for audit.")

Excluded record saved for audit.

In [ ]:
final_missing = (
    df_model[
        MODEL_B_FEATURES + ["employment_outcome"]
    ]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    final_missing.to_frame("missing_count")
)

                                missing_count
analytical_thinking                         0
resilience_flexibility_agility              0
leadership_social_influence                 0
creative_thinking                           0
motivation_self_awareness                   0
technological_literacy                      0
empathy_active_listening                    0
curiosity_lifelong_learning                 0
talent_management                           0
service_orientation                         0
age                                         0
gender                                      0
marital_status                              0
household_size                              0
education_level                             0
field_of_study                              0
time_since_studies                          0
province                                    0
digital_access                              0
english_communication                       0
digital_confidence                          0
formal_training                             0
training_type                               0
training_field                              0
training_duration                           0
training_relevance                          0
employment_outcome                          0

In [ ]:
target_summary = pd.DataFrame({
    "count": df_model["employment_outcome"]
        .value_counts()
        .sort_index(),

    "percentage": df_model["employment_outcome"]
        .value_counts(normalize=True)
        .sort_index()
        .mul(100)
        .round(2)
})

display(target_summary)

print("Final modelling sample:", len(df_model))

                    count  percentage
employment_outcome
0                     101       52.88
1                      90       47.12

Final modelling sample: 191

In [ ]:
OUTPUT_PATH = (
    PROCESSED_DIR
    / "primary_model_dataset_prepared.csv"
)

df_model.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Final prepared modelling dataset saved:")
print(OUTPUT_PATH)
print("Shape:", df_model.shape)

Final prepared modelling dataset saved:
/content/processed/primary_model_dataset_prepared.csv
Shape: (191, 52)

In [ ]:
excluded_features = pd.DataFrame([
    {
        "survey_question": "Q10",
        "feature": "languages_read_write",
        "reason": (
            "Excluded for parsimony; English communication was retained "
            "as the more directly measured communication-capability variable."
        )
    },
    {
        "survey_question": "Q13",
        "feature": "internet_use_frequency",
        "reason": (
            "Excluded because frequency of internet use does not directly "
            "represent digital capability; digital access and digital "
            "confidence were retained."
        )
    },
    {
        "survey_question": "Q19",
        "feature": "reason_no_training",
        "reason": (
            "Conditional barrier variable collected only from respondents "
            "without formal training; retained for descriptive analysis "
            "rather than primary prediction."
        )
    }
])

display(excluded_features)

,survey_question,feature,reason
0,Q10,languages_read_write,Excluded for parsimony; English communication ...
1,Q13,internet_use_frequency,Excluded because frequency of internet use doe...
2,Q19,reason_no_training,Conditional barrier variable collected only fr...

In [ ]:
feature_rows = []

# Model A: 10 skill variables
for feature in MODEL_A_FEATURES:
    feature_rows.append({
        "feature": feature,
        "construct_group": "Skill",
        "model_a": True,
        "model_b": True
    })

# Model B additional variables
groups = {
    "age": "Demographic",
    "gender": "Demographic",
    "marital_status": "Demographic",
    "household_size": "Demographic",

    "education_level": "Education / human capital",
    "field_of_study": "Education / human capital",
    "time_since_studies": "Education / human capital",

    "province": "Structural / contextual",
    "digital_access": "Structural / contextual",
    "english_communication": "Structural / capability",
    "digital_confidence": "Structural / capability",

    "formal_training": "Training",
    "training_type": "Training",
    "training_field": "Training",
    "training_duration": "Training",
    "training_relevance": "Training",
}

for feature in MODEL_B_ADDITIONAL_FEATURES:
    feature_rows.append({
        "feature": feature,
        "construct_group": groups[feature],
        "model_a": False,
        "model_b": True
    })

feature_specification = pd.DataFrame(feature_rows)

print("Feature specification created.")
print("Number of rows:", len(feature_specification))

display(feature_specification)

Feature specification created.
Number of rows: 26

,feature,construct_group,model_a,model_b
0,analytical_thinking,Skill,True,True
1,resilience_flexibility_agility,Skill,True,True
2,leadership_social_influence,Skill,True,True
3,creative_thinking,Skill,True,True
4,motivation_self_awareness,Skill,True,True
5,technological_literacy,Skill,True,True
6,empathy_active_listening,Skill,True,True
7,curiosity_lifelong_learning,Skill,True,True
8,talent_management,Skill,True,True
9,service_orientation,Skill,True,True
10,age,Demographic,False,True
11,gender,Demographic,False,True
12,marital_status,Demographic,False,True
13,household_size,Demographic,False,True
14,education_level,Education / human capital,False,True
15,field_of_study,Education / human capital,False,True
16,time_since_studies,Education / human capital,False,True
17,province,Structural / contextual,False,True
18,digital_access,Structural / contextual,False,True
19,english_communication,Structural / capability,False,True
20,digital_confidence,Structural / capability,False,True
21,formal_training,Training,False,True
22,training_type,Training,False,True
23,training_field,Training,False,True
24,training_duration,Training,False,True
25,training_relevance,Training,False,True

In [ ]:
feature_specification.to_csv(
    PROCESSED_DIR / "model_feature_specification.csv",
    index=False,
    encoding="utf-8-sig"
)

excluded_features.to_csv(
    PROCESSED_DIR / "excluded_feature_specification.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Feature documentation saved successfully.")

Feature documentation saved successfully.

In [ ]:
GENDER_MAP = {
    # English
    "Male": "Male",
    "Female": "Female",
    "Prefer not to say": "Prefer not to say",

    # Sinhala
    "පුරුෂ": "Male",
    "ස්ත්‍රී": "Female",
    "පැවසීමට අකමැති": "Prefer not to say",

    # Tamil
    "ஆண்": "Male",
    "பெண்": "Female",
    "கூற விரும்பவில்லை": "Prefer not to say",
}

df_model["gender"] = df_model["gender"].map(GENDER_MAP)

print(df_model["gender"].value_counts(dropna=False))

gender
Female    100
Male       91
Name: count, dtype: int64

In [ ]:
MARITAL_STATUS_MAP = {
    # English
    "Never married": "Never married",
    "Married": "Married",
    "Widowed": "Widowed",
    "Divorced / Separated": "Divorced / Separated",
    "Prefer not to say": "Prefer not to say",

    # Sinhala
    "කිසිදා විවාහ වී නොමැත": "Never married",
    "විවාහකයි": "Married",
    "වැන්දඹු": "Widowed",
    "දික්කසාද වී / වෙන් වී ඇත": "Divorced / Separated",
    "පැවසීමට අකමැති": "Prefer not to say",

    # Tamil
    "ஒருபோதும் திருமணம் ஆகவில்லை": "Never married",
    "திருமணமானவர்": "Married",
    "விதவை / விதவர்": "Widowed",
    "விவாகரத்து / பிரிந்து வாழ்பவர்": "Divorced / Separated",
    "கூற விரும்பவில்லை": "Prefer not to say",
}

df_model["marital_status"] = (
    df_model["marital_status"]
    .map(MARITAL_STATUS_MAP)
)

print(df_model["marital_status"].value_counts(dropna=False))

marital_status
Never married           159
Married                  24
Prefer not to say         6
Divorced / Separated      1
Widowed                   1
Name: count, dtype: int64

In [ ]:
EDUCATION_MAP = {
    # English
    "G.C.E. Ordinary Level (O/Level)": "GCE O-Level",
    "G.C.E. Advanced Level (A/Level)": "GCE A-Level",
    "Certificate Level / Vocational Training": "Certificate / Vocational Training",
    "Diploma / Higher National Diploma": "Diploma / HND",
    "Bachelor’s Degree": "Bachelor's Degree",
    "Postgraduate Qualification": "Postgraduate Qualification",

    # Sinhala
    "G.C.E සාමාන්‍ය පෙළ (O/L)": "GCE O-Level",
    "G.C.E උසස් පෙළ (A/L)": "GCE A-Level",
    "සහතික පාඨමාලා / වෘත්තීය පුහුණුව": "Certificate / Vocational Training",
    "ඩිප්ලෝමා / උසස් ජාතික ඩිප්ලෝමා": "Diploma / HND",
    "උපාධිය": "Bachelor's Degree",
    "පශ්චාත් උපාධි සුදුසුකම්": "Postgraduate Qualification",

    # Tamil
    "G.C.E சாதாரண தரம் (O/L)": "GCE O-Level",
    "G.C.E உயர்தரம் (A/L)": "GCE A-Level",
    "சான்றிதழ் நிலை / தொழிற்பயிற்சி": "Certificate / Vocational Training",
    "டிப்ளோமா / உயர் தேசிய டிப்ளோமா": "Diploma / HND",
    "இளங்கலை பட்டம்": "Bachelor's Degree",
    "முதுகலை தகுதி": "Postgraduate Qualification",
}

df_model["education_level"] = (
    df_model["education_level"]
    .map(EDUCATION_MAP)
)

print(df_model["education_level"].value_counts(dropna=False))

education_level
GCE A-Level                          63
GCE O-Level                          43
Diploma / HND                        34
Certificate / Vocational Training    30
Bachelor's Degree                    19
Postgraduate Qualification            2
Name: count, dtype: int64

In [ ]:
FIELD_OF_STUDY_MAP = {
    # English
    "Information Technology / Computer Science": "IT / Computer Science",
    "Business / Commerce / Management": "Business / Commerce / Management",
    "Engineering / Technology": "Engineering / Technology",
    "Vocational Trades": "Vocational Trades",
    "Arts / Humanities / Social Sciences": "Arts / Humanities / Social Sciences",
    "Science / Mathematics": "Science / Mathematics",
    "General Education / No specialization yet": "General Education / No specialization",

    # Sinhala
    "තොරතුරු තාක්ෂණය / පරිගණක විද්‍යාව": "IT / Computer Science",
    "ව්‍යාපාර / වෙළඳාම / කළමනාකරණය": "Business / Commerce / Management",
    "ඉංජිනේරු / තාක්ෂණය": "Engineering / Technology",
    "වෘත්තීය කුසලතා (උදා: ආහාරපාන සේවා, යාන්ත්‍රික, ඉදිකිරීම්)": "Vocational Trades",
    "කලා / මානව විද්‍යා / සමාජ විද්‍යා": "Arts / Humanities / Social Sciences",
    "විද්‍යා / ගණිතය": "Science / Mathematics",
    "සාමාන්‍ය අධ්‍යාපනය / විශේෂීකරණයක් නොමැත": "General Education / No specialization",

    # Tamil
    "தகவல் தொழில்நுட்பம் / கணினி அறிவியல்": "IT / Computer Science",
    "வணிகம் / வர்த்தகம் / மேலாண்மை": "Business / Commerce / Management",
    "பொறியியல் / தொழில்நுட்பம்": "Engineering / Technology",
    "தொழில் திறன்கள் (உதா: விருந்தோம்பல், இயந்திரவியல், கட்டுமானம்)": "Vocational Trades",
    "கலை / மனிதநேயம் / சமூக அறிவியல்": "Arts / Humanities / Social Sciences",
    "அறிவியல் / கணிதம்": "Science / Mathematics",
    "பொதுக் கல்வி / குறிப்பிட்ட சிறப்பு இல்லை": "General Education / No specialization",
}

df_model["field_of_study"] = (
    df_model["field_of_study"]
    .map(FIELD_OF_STUDY_MAP)
)

print(df_model["field_of_study"].value_counts(dropna=False))

field_of_study
Arts / Humanities / Social Sciences      44
IT / Computer Science                    40
Business / Commerce / Management         35
Vocational Trades                        32
General Education / No specialization    21
Science / Mathematics                    11
Engineering / Technology                  8
Name: count, dtype: int64

In [ ]:
TIME_SINCE_STUDIES_MAP = {
    # English
    "Less than 6 months": "Less than 6 months",
    "6-12 months": "6-12 months",
    "More than 12 months": "More than 12 months",
    "Not completed yet": "Not completed yet",

    # Sinhala
    "මාස 6කට වඩා අඩුයි": "Less than 6 months",
    "මාස 6ත් 12ත් අතර": "6-12 months",
    "මාස 12කට වඩා වැඩියි": "More than 12 months",
    "තවම අවසන් කර නොමැත": "Not completed yet",

    # Tamil
    "6 மாதங்களுக்கும் குறைவாக": "Less than 6 months",
    "6 - 12 மாதங்கள்": "6-12 months",
    "12 மாதங்களுக்கும் அதிகம்": "More than 12 months",
    "இன்னும் முடிக்கப்படவில்லை": "Not completed yet",
}

df_model["time_since_studies"] = (
    df_model["time_since_studies"]
    .map(TIME_SINCE_STUDIES_MAP)
)

print(df_model["time_since_studies"].value_counts(dropna=False))

time_since_studies
More than 12 months    94
6-12 months            45
Not completed yet      34
Less than 6 months     18
Name: count, dtype: int64

In [ ]:
PROVINCE_MAP = {
    # English
    "Western": "Western",
    "Central": "Central",
    "Southern": "Southern",
    "North Western": "North Western",
    "Sabaragamuwa": "Sabaragamuwa",
    "North Central": "North Central",
    "Uva": "Uva",
    "Eastern": "Eastern",
    "Northern": "Northern",

    # Sinhala
    "බස්නාහිර": "Western",
    "මධ්‍යම": "Central",
    "දකුණු": "Southern",
    "වයඹ": "North Western",
    "සබරගමුව": "Sabaragamuwa",
    "උතුරු මැද": "North Central",
    "ඌව": "Uva",
    "නැගෙනහිර": "Eastern",
    "උතුරු": "Northern",

    # Tamil
    "மேற்கு": "Western",
    "மத்திய": "Central",
    "தெற்கு": "Southern",
    "வடமேற்கு": "North Western",
    "சபரகமுவ": "Sabaragamuwa",
    "வடமத்திய": "North Central",
    "ஊவா": "Uva",
    "கிழக்கு": "Eastern",
    "வடக்கு": "Northern",
}

df_model["province"] = df_model["province"].map(PROVINCE_MAP)

print(df_model["province"].value_counts(dropna=False))

province
Central          84
Uva              31
Northern         23
Western          22
Eastern          20
Southern          5
Sabaragamuwa      3
North Western     3
Name: count, dtype: int64

In [ ]:
DIGITAL_ACCESS_MAP = {
    # English
    "No access / Very unreliable": "No access / Very unreliable",
    "Limited access (Mobile only)": "Limited access",
    "Average": "Average",
    "Good (Regular access)": "Good",
    "Excellent (Unrestricted access)": "Excellent",

    # Sinhala
    "කිසිදු ප්‍රවේශයක් නැත / ඉතා අවිශ්වාසදායකයි": "No access / Very unreliable",
    "සීමිත ප්‍රවේශයක් (උදා: දුරකථනයෙන් පමණි)": "Limited access",
    "සාමාන්‍යයි": "Average",
    "හොඳයි (නිතිපතා ප්‍රවේශය ඇත)": "Good",
    "ඉතා හොඳයි (බාධාවකින් තොර ප්‍රවේශය ඇත)": "Excellent",

    # Tamil
    "அணுகல் இல்லை / மிகவும் நம்பகமற்றது": "No access / Very unreliable",
    "வரையறுக்கப்பட்ட அணுகல் (மொபைல் மட்டும்)": "Limited access",
    "சராசரி": "Average",
    "நல்லது (வழக்கமான அணுகல்)": "Good",
    "மிகவும் நல்லது (வரம்பற்ற அணுகல்)": "Excellent",
}

df_model["digital_access"] = (
    df_model["digital_access"]
    .map(DIGITAL_ACCESS_MAP)
)

print(df_model["digital_access"].value_counts(dropna=False))

digital_access
Limited access                 65
Good                           48
Average                        47
Excellent                      28
No access / Very unreliable     3
Name: count, dtype: int64

In [ ]:
TRAINING_TYPE_MAP = {
    "NVQ": "NVQ",

    # Certificate
    "Certificate course": "Certificate course",
    "සහතික පාඨමාලාව": "Certificate course",
    "சான்றிதழ் பாடநெறி": "Certificate course",

    # Diploma
    "Diploma": "Diploma",
    "ඩිප්ලෝමාව": "Diploma",
    "டிப்ளோமா": "Diploma",

    # Higher Diploma
    "Higher Diploma": "Higher Diploma",
    "උසස් ඩිප්ලෝමාව": "Higher Diploma",
    "உயர் டிப்ளோமா": "Higher Diploma",

    # Professional
    "Professional qualification": "Professional qualification",
    "වෘත්තීය සුදුසුකම": "Professional qualification",
    "தொழில்முறை தகுதி": "Professional qualification",

    # Apprenticeship
    "Apprenticeship / Technical training": "Apprenticeship / Technical training",
    "ආධුනිකත්ව / තාක්ෂණික පුහුණුව": "Apprenticeship / Technical training",
    "பயிற்சிநிலை / தொழில்நுட்பப் பயிற்சி": "Apprenticeship / Technical training",

    # Other
    "Other": "Other",
    "වෙනත්": "Other",
    "வேறு": "Other",

    # Structural non-applicability
    "NOT_APPLICABLE_NO_FORMAL_TRAINING":
        "NOT_APPLICABLE_NO_FORMAL_TRAINING",
}

df_model["training_type"] = (
    df_model["training_type"]
    .map(TRAINING_TYPE_MAP)
)

print(df_model["training_type"].value_counts(dropna=False))

training_type
NOT_APPLICABLE_NO_FORMAL_TRAINING      100
NVQ                                     45
Diploma                                 12
Higher Diploma                          11
Professional qualification              10
Certificate course                       6
Apprenticeship / Technical training      4
Other                                    3
Name: count, dtype: int64

In [ ]:
TRAINING_FIELD_MAP = {
    "Information Technology": "Information Technology",
    "තොරතුරු තාක්ෂණය": "Information Technology",
    "தகவல் தொழில்நுட்பம்": "Information Technology",

    "Business / Management": "Business / Management",
    "ව්‍යාපාර / කළමනාකරණය": "Business / Management",
    "வணிகம் / மேலாண்மை": "Business / Management",

    "Hospitality / Tourism": "Hospitality / Tourism",
    "ආගන්තුක සත්කාර / සංචාරක ව්‍යාපාරය": "Hospitality / Tourism",
    "விருந்தோம்பல் / சுற்றுலா": "Hospitality / Tourism",

    "Construction": "Construction",
    "ඉදිකිරීම්": "Construction",
    "கட்டுமானம்": "Construction",

    "Automobile / Mechanical": "Automobile / Mechanical",
    "මෝටර් රථ / යාන්ත්‍රික": "Automobile / Mechanical",
    "வாகன / இயந்திரவியல்": "Automobile / Mechanical",

    "Electrical / Electronics": "Electrical / Electronics",
    "විදුලි / ඉලෙක්ට්‍රොනික": "Electrical / Electronics",
    "மின்சாரம் / மின்னணுவியல்": "Electrical / Electronics",

    "Beauty / Personal Care": "Beauty / Personal Care",
    "රූපලාවණ්‍ය / පුද්ගලික සත්කාර": "Beauty / Personal Care",
    "அழகு / தனிப்பட்ட பராமரிப்பு": "Beauty / Personal Care",

    "Agriculture": "Agriculture",
    "කෘෂිකර්මය": "Agriculture",
    "விவசாயம்": "Agriculture",

    "Healthcare": "Healthcare",
    "සෞඛ්‍ය සේවා": "Healthcare",
    "சுகாதாரம்": "Healthcare",

    "Other": "Other",
    "වෙනත්": "Other",
    "வேறு": "Other",

    "NOT_APPLICABLE_NO_FORMAL_TRAINING":
        "NOT_APPLICABLE_NO_FORMAL_TRAINING",
}

df_model["training_field"] = (
    df_model["training_field"]
    .map(TRAINING_FIELD_MAP)
)

print(df_model["training_field"].value_counts(dropna=False))

training_field
NOT_APPLICABLE_NO_FORMAL_TRAINING    100
Agriculture                           20
Information Technology                19
Other                                 17
Hospitality / Tourism                 11
Business / Management                 10
Construction                           5
Healthcare                             4
Beauty / Personal Care                 3
Automobile / Mechanical                2
Name: count, dtype: int64

In [ ]:
TRAINING_DURATION_MAP = {
    "Less than 3 months": "Less than 3 months",
    "මාස 3කට අඩු": "Less than 3 months",
    "3 மாதங்களுக்கும் குறைவாக": "Less than 3 months",

    "3–6 months": "3-6 months",
    "මාස 3–6": "3-6 months",
    "3–6 மாதங்கள்": "3-6 months",

    "6–12 months": "6-12 months",
    "මාස 6–12": "6-12 months",
    "6–12 மாதங்கள்": "6-12 months",

    "More than 1 year": "More than 1 year",
    "වසර 1කට වැඩි": "More than 1 year",
    "1 வருடத்திற்கும் மேல்": "More than 1 year",

    "NOT_APPLICABLE_NO_FORMAL_TRAINING":
        "NOT_APPLICABLE_NO_FORMAL_TRAINING",
}

df_model["training_duration"] = (
    df_model["training_duration"]
    .map(TRAINING_DURATION_MAP)
)

print(df_model["training_duration"].value_counts(dropna=False))

training_duration
NOT_APPLICABLE_NO_FORMAL_TRAINING    100
6-12 months                           40
More than 1 year                      29
3-6 months                            13
Less than 3 months                     9
Name: count, dtype: int64

In [ ]:
TRAINING_RELEVANCE_MAP = {
    "Not relevant": "Not relevant",
    "අදාළ නොවේ": "Not relevant",
    "தொடர்பில்லை": "Not relevant",

    "Slightly relevant": "Slightly relevant",
    "සුළු වශයෙන් අදාළයි": "Slightly relevant",
    "சிறிதளவு தொடர்புடையது": "Slightly relevant",

    "Moderately relevant": "Moderately relevant",
    "මධ්‍යස්ථව අදාළයි": "Moderately relevant",
    "மிதமாக தொடர்புடையது": "Moderately relevant",

    "Very relevant": "Very relevant",
    "ඉතා අදාළයි": "Very relevant",
    "மிகவும் தொடர்புடையது": "Very relevant",

    "Highly relevant": "Highly relevant",
    "අතිශයින් අදාළයි": "Highly relevant",
    "மிக அதிகமாக தொடர்புடையது": "Highly relevant",

    "NOT_APPLICABLE_NO_FORMAL_TRAINING":
        "NOT_APPLICABLE_NO_FORMAL_TRAINING",
}

df_model["training_relevance"] = (
    df_model["training_relevance"]
    .map(TRAINING_RELEVANCE_MAP)
)

print(df_model["training_relevance"].value_counts(dropna=False))

training_relevance
NOT_APPLICABLE_NO_FORMAL_TRAINING    100
Very relevant                         46
Highly relevant                       21
Moderately relevant                   14
Slightly relevant                      8
Not relevant                           2
Name: count, dtype: int64

In [ ]:
final_missing = (
    df_model[
        MODEL_B_FEATURES + ["employment_outcome"]
    ]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    final_missing.to_frame("missing_count")
)

                                missing_count
analytical_thinking                         0
resilience_flexibility_agility              0
leadership_social_influence                 0
creative_thinking                           0
motivation_self_awareness                   0
technological_literacy                      0
empathy_active_listening                    0
curiosity_lifelong_learning                 0
talent_management                           0
service_orientation                         0
age                                         0
gender                                      0
marital_status                              0
household_size                              0
education_level                             0
field_of_study                              0
time_since_studies                          0
province                                    0
digital_access                              0
english_communication                       0
digital_confidence                          0
formal_training                             0
training_type                               0
training_field                              0
training_duration                           0
training_relevance                          0
employment_outcome                          0

In [ ]:
CATEGORICAL_MODEL_B_FEATURES = [
    "gender",
    "marital_status",
    "education_level",
    "field_of_study",
    "time_since_studies",
    "province",
    "digital_access",
    "formal_training",
    "training_type",
    "training_field",
    "training_duration",
    "training_relevance",
]

for col in CATEGORICAL_MODEL_B_FEATURES:
    print("\n" + "=" * 70)
    print(col)
    print(df_model[col].value_counts(dropna=False))

======================================================================
gender
gender
Female    100
Male       91
Name: count, dtype: int64

======================================================================
marital_status
marital_status
Never married           159
Married                  24
Prefer not to say         6
Divorced / Separated      1
Widowed                   1
Name: count, dtype: int64

======================================================================
education_level
education_level
GCE A-Level                          63
GCE O-Level                          43
Diploma / HND                        34
Certificate / Vocational Training    30
Bachelor's Degree                    19
Postgraduate Qualification            2
Name: count, dtype: int64

======================================================================
field_of_study
field_of_study
Arts / Humanities / Social Sciences      44
IT / Computer Science                    40
Business / Commerce / Management         35
Vocational Trades                        32
General Education / No specialization    21
Science / Mathematics                    11
Engineering / Technology                  8
Name: count, dtype: int64

======================================================================
time_since_studies
time_since_studies
More than 12 months    94
6-12 months            45
Not completed yet      34
Less than 6 months     18
Name: count, dtype: int64

======================================================================
province
province
Central          84
Uva              31
Northern         23
Western          22
Eastern          20
Southern          5
Sabaragamuwa      3
North Western     3
Name: count, dtype: int64

======================================================================
digital_access
digital_access
Limited access                 65
Good                           48
Average                        47
Excellent                      28
No access / Very unreliable     3
Name: count, dtype: int64

======================================================================
formal_training
formal_training
No     100
Yes     91
Name: count, dtype: int64

======================================================================
training_type
training_type
NOT_APPLICABLE_NO_FORMAL_TRAINING      100
NVQ                                     45
Diploma                                 12
Higher Diploma                          11
Professional qualification              10
Certificate course                       6
Apprenticeship / Technical training      4
Other                                    3
Name: count, dtype: int64

======================================================================
training_field
training_field
NOT_APPLICABLE_NO_FORMAL_TRAINING    100
Agriculture                           20
Information Technology                19
Other                                 17
Hospitality / Tourism                 11
Business / Management                 10
Construction                           5
Healthcare                             4
Beauty / Personal Care                 3
Automobile / Mechanical                2
Name: count, dtype: int64

======================================================================
training_duration
training_duration
NOT_APPLICABLE_NO_FORMAL_TRAINING    100
6-12 months                           40
More than 1 year                      29
3-6 months                            13
Less than 3 months                     9
Name: count, dtype: int64

======================================================================
training_relevance
training_relevance
NOT_APPLICABLE_NO_FORMAL_TRAINING    100
Very relevant                         46
Highly relevant                       21
Moderately relevant                   14
Slightly relevant                      8
Not relevant                           2
Name: count, dtype: int64

In [ ]:
print("FINAL DATASET CHECK")
print("=" * 50)

print("Respondents:", len(df_model))

print("\nTarget distribution:")
print(
    df_model["employment_outcome"]
    .value_counts()
    .sort_index()
)

print("\nTarget percentages:")
print(
    df_model["employment_outcome"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print("\nModel A feature count:", len(MODEL_A_FEATURES))
print("Model B feature count:", len(MODEL_B_FEATURES))

print(
    "\nDuplicate respondent IDs:",
    df_model["respondent_id"].duplicated().sum()
)

print(
    "\nTotal missing values in Model A:",
    df_model[MODEL_A_FEATURES].isna().sum().sum()
)

print(
    "Total missing values in Model B:",
    df_model[MODEL_B_FEATURES].isna().sum().sum()
)

FINAL DATASET CHECK
==================================================
Respondents: 191

Target distribution:
employment_outcome
0    101
1     90
Name: count, dtype: int64

Target percentages:
employment_outcome
0    52.88
1    47.12
Name: proportion, dtype: float64

Model A feature count: 10
Model B feature count: 26

Duplicate respondent IDs: 0

Total missing values in Model A: 0
Total missing values in Model B: 0

In [ ]:
OUTPUT_PATH = (
    PROCESSED_DIR
    / "primary_model_dataset_prepared.csv"
)

df_model.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("FINAL prepared modelling dataset saved:")
print(OUTPUT_PATH)
print("Shape:", df_model.shape)

FINAL prepared modelling dataset saved:
/content/processed/primary_model_dataset_prepared.csv
Shape: (191, 52)

In [ ]:
feature_specification.to_csv(
    PROCESSED_DIR / "model_feature_specification.csv",
    index=False,
    encoding="utf-8-sig"
)

excluded_features.to_csv(
    PROCESSED_DIR / "excluded_feature_specification.csv",
    index=False,
    encoding="utf-8-sig"
)

df_missing_core_skills.to_csv(
    PROCESSED_DIR / "excluded_missing_core_skills.csv",
    index=False,
    encoding="utf-8-sig"
)

print("All preprocessing documentation saved.")

All preprocessing documentation saved.